version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_HOST: 'db'
      POSTGRES_PORT: 5432
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: bash -c "cd anverali && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/anverali
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      SECRET_KEY: 'django-insecure-^q#86@1aji@=-ynqij(hf#hqnw6e*@$*p4!w=@h)dh-8ao(stv'
      POSTGRES_DB: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_HOST: 'db'
      POSTGRES_PORT: 5432

volumes:
  postgres_data: